apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: loja-veloz
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: loja-veloz
        metrics_path: /metrics
        static_configs:
          - targets:
              - gateway:3000
              - pedidos:3001
              - pagamentos:3002
              - estoque:3003

