apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: loja-veloz
  labels:
    app.kubernetes.io/name: jaeger
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: ui
      nodePort: 30686
      protocol: TCP

