apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: loja-veloz
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
    - name: health
      port: 13133
      targetPort: health
      protocol: TCP

