apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: loja-veloz
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: loja-veloz
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP

