apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-config
  namespace: loja-veloz
data:
  PORT: "3001"
  HOST: 0.0.0.0
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: loja_veloz

