apiVersion: v1
kind: Service
metadata:
  name: estoque
  namespace: loja-veloz
  labels:
    app.kubernetes.io/name: estoque
    app.kubernetes.io/part-of: loja-veloz
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: estoque
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP

